name: py311
channels:
  - defaults
  - conda-forge
dependencies:
  - earthengine-api>=1.5.13
  - geopandas>=0.14.4
  - jupyterlab>=4.3.2
  - pandas>=2.2.2
  - polars>=1.35.1
  - numpy>=1.26.4
  - python=3.11
  - refet
  - xarray
  - netcdf4
  - joblib>=1.5.3
  - tqdm>=4.67.1


