# Post Processing configuration file for the DRI-OWRD Statewide ET Project

[INPUTS]

# root directory where this code repository is located on the local file system
root_directory = C:\Users\bminor\Documents\GitHub\dri-owrd-et
#root_directory = /Users/blakeminor/Documents/GitHub/dri-owrd-et

# field_boundary shapefile name (must be located within the "shapefiles" subfolder for pre- & post-processing)
field_boundary_shapefile_name = Oregon_Hyd_Area_Ag_Boundaries_20241016.shp

# unique ID column/attribute for the field boundary dataset
unique_field_id = OPENET_ID

# watershed HUC-level to aggregate field summaries by (HUC8 or HUC12 only)
# summaries for multiple irrigation source types (all, groundwater, and surface water) will be prepared  
huc_level = HUC12

# start and end years to process data for
# 1985-2025 available (as of April 2026)
# NOTE: For Step 3 (Gap Filling) - EToF CLIMATOLOGY WINDOW OPTIONS: 1985-1991, 1992-1997, 1998-2003, 2004-2009, 2010-2015, 2016-2021 
# NOTE: 2016-2021 climo is used for 2022, 2023, 2024, and 2025 gap-filling, so just extend the end year for the desired processing time period on the last gap filling window
start_year = 1985
end_year = 1991

# flag to process data for an individual field/HUC (True) or the entire field boundary/HUC datasets (False)
test_flag = True