# Post Processing configuration file for the DRI-OWRD Statewide ET Project

[INPUTS]

# root directory where this code repository is located on the local file system
root_directory = C:\Users\bminor\Documents\GitHub\dri-owrd-et
#root_directory = /Users/blakeminor/Documents/GitHub/dri-owrd-et

# field_boundary shapefile name (must be located within the "shapefiles" subfolder for pre- & post-processing)
field_boundary_shapefile_name = Oregon_Hyd_Area_Ag_Boundaries_20241016.shp

# unique ID column/attribute for the field boundary dataset
unique_field_id = OPENET_ID

# Watershed HUC-level to use for small pond evaporation exports (HUC8 or HUC12 only)
huc_level = HUC12

# start and end years to extract data for (only used for field boundary exports, not HUC watershed evaporation exports)
# 1985-2024 available (as of March 2026); recommend running one year at first to limit compute costs
start_year = 1985
end_year = 1985


[ZONAL_STATS]

# monthly data variable to extract for the field boundary dataset (et, et_reference, et_fraction, or ppt)
monthly_variable = et

# annual data variable to extract for the field boundary dataset (crop_type, irrmapper_irrigated, irrmapper_wetland, or etof_irr_status)
# crop type is based on the Cropland Data Layer
# irrmapper and etof variables are used to determine irrigation status
annual_variable = crop_type

# flag to export data for an individual field/HUC (True) or the entire field boundary/HUC datasets (False)
test_flag = True