# Earth Engine zonal stats export configuration file for the DRI-OWRD Statewide ET Project

[INPUTS]
# root directory where this code repository is located on the local file system
root_directory = C:\Users\bminor\Documents\GitHub\dri-owrd-et
#root_directory = /Users/blakeminor/Documents/GitHub/dri-owrd-et

# Google Cloud Project ID (a registered cloud project is required for any earth engine exports)
gcloud_project_id = ee-bminor

# field boundary Earth Engine assetID in Earth Engine upload after pre-processing has been completed
field_boundary_asset_id = projects/openet/field_boundaries/Oregon_Hyd/Oregon_Hyd_Area_Ag_Boundaries_20240501

# unique ID column/attribute for the field boundary dataset
unique_field_id = OPENET_ID

# HUC-level to use for small pond evaporation exports (HUC8 or HUC12 only)
huc_level = HUC12

# start and end years to extract data for (only used for field boundary exports, not HUC watershed evaporation exports)
# 1985-2024 available (as of March 2026); recommend running one year at first to limit compute costs
start_year = 1985
end_year = 1985

# start and end years to extract EToF climatology data (used for gap-filling missing months of EToF for field boundaries)
# EToF CLIMATOLOGY WINDOW OPTIONS: 1984-1991, 1992-1997, 1998-2003, 2004-2009, 2010-2015, 2016-2021 (NOTE: 2016-2021 climo is used for 2022, 2023, and 2024 gap-filling; do not need to extend the climo end year beyond 2021)
start_year_climo = 1984
end_year_climo = 1991

# flag to export/process data for an individual field/HUC (True) or the entire field boundary/HUC datasets (False)
test_flag = True


[ZONAL_STATS]

# monthly data variable to extract for the field boundary dataset (et, et_reference, et_fraction, or ppt)
monthly_variable = et

# annual data variable to extract for the field boundary dataset (crop_type, irrmapper_irrigated, irrmapper_wetland, or etof_irr_status)
# crop type is based on the Cropland Data Layer
# irrmapper and etof variables are used to determine irrigation status
annual_variable = crop_type

# table export location (google_drive or cloud_storage)
export_location = google_drive

# google drive folder name (only used if exporting to google drive)
gdrive_folder = oregon_exports

# google cloud storage bucket name (only used if exporting to google cloud storage)
gcloud_bucket = openet

# google cloud storage path within the bucket (only used if exporting to google cloud storage)
gcloud_bucket_path = intercomparison/output_main/Oregon_Statewide_2023/field_summaries/historical